config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :links
  resources :views, path: "v", only: [:show]
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/base62.rb
class Base62
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return ALPHABET[0] if number == 0 # special case
    result = ""

    while number > 0
      result = ALPHABET[number % BASE] + result
      number /= BASE
    end

    result
  end

  def self.decode(string)
    number = 0
    string.each_char { |char| number = number * BASE + ALPHABET.index(char) }
    number
  end
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  belongs_to :user, optional: true
  scope :recent_first, -> { order(created_at: :desc) }
  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find(id)
    super Base62.decode(id)
  end

  def to_param
    Base62.encode(id)
  end

  def domain
    URI.parse(url).host
    rescue URI::InvalidURIError
  end
end

app/models/metadata.rb
require 'open-uri'

class Metadata
  attr_reader :doc

  def self.retrieve_from(url)
    new(URI.open(url))
  rescue StandardError
    new(nil)
  end

  def initialize(html = nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css('title')&.text
  end

  def description
    meta_tag_content 'description'
  end

  def image
    meta_tag_content 'og:image', name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch('content', nil)&.text
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links, dependent: :destroy
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :allow_editing_link, only: [:edit, :update, :destroy]

  def index
    if current_user
      @links = current_user.links.recent_first if current_user
    else
      @links = Link.recent_first
    end
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.user = current_user
    if @link.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream { render turbo_stream: turbo_stream.prepend("links", @link) }
      end
    else
      index # this is added because index.html needs @links and @link
      render :index, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path
    flash[:notice] = "Link was successfully destroyed."
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def allow_editing_link
    redirect_to root_path unless @link.user == current_user
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: "The link you tried to access does not exist."
  end

  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end

  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <%= tag.p alert, class:"bg-yellow-100 text-yellow-800 rounded px-4 py-2" if alert %>
      <%= tag.p notice, class:"bg-blue-100 text-blue-800 rounded px-4 py-2" if notice %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, required: true, autofocus: true, placeholder: "http://example.com", class: "flex-grow rounded" %>
    <%= form.button class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= turbo_stream_from link %>
  <div class="grid grid-cols-8 items-center py-4">
    <div class="col-span-5">
      <%= link_to view_path(link), target: :_blank, data: {turbo: false}, class: "no-underline" do %>
        <%= favicon_image_tag link.domain, class: "inline-block m-0" %>
        <%= link.title || link.url %>
        <%= tag.div link.description, class: "text-xs text-gray-500" %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>

    <div class="col-span-2 text-center text-xs">
      <%= link_to pluralize(link.views_count, "view"), link, class: "px-2 py-1.5 rounded bg-gray-100 no-underline" %>
    </div>

    <div class="text-center text-xs">
      <%= button_tag "Copy", class: "font-medium px-2 py-1.5 rounded bg-gray-100 no-underline", data: {controller: "clipboard", clipboard_text: view_url(link)} %>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<%= link_to "<-Back", root_path, class: "text-blue-600 no-underline" %>
<h1>Edit Link</h1>

<%= render partial: "form", locals: { link: @link } %>

<div class="flex gap-1 mt-4">
  <%= link_to "Cancel", @link %>
  or
  <%= button_to "Delete", @link, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/links/index.html.erb
<nav class="flex items-baseline justify-between">
  <h1>URL Shortener</h1>
  <div class="flex gap-2">
    <% if current_user %>
      <%= link_to "Profile", edit_user_password_path %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>

  </div>
</nav>


<%= render partial: "form", locals: { link: @link } %>

<div id="links" class="mt-8 flex flex-col gap-4 divide-y divide-gray-100">
  <%= render @links %>
</div>

app/views/links/show.html.erb
<%= link_to "<-Back", root_path, class: "text-blue-600 no-underline" %>
<br><br>
<h1><%= @link.url %></h1>

<%= link_to "Edit", edit_link_path(@link) if current_user %>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>